AppBundle\Entity\Cycle:
    type: entity
    table: cycle
    repositoryClass: AppBundle\Repository\CycleRepository
    indexes:
        position_index:
            columns: [ position ]
    oneToMany:
        packs:
            orderBy: { 'position': 'ASC' }
            targetEntity: Pack
            mappedBy: cycle
            fetch: EAGER
    manyToMany:
        rotations:
            targetEntity: Rotation
            mappedBy: rotated
            cascade: ["remove"]
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            unique: true
            length: 20
            nullable: false
        name:
            type: string
            length: 255
            nullable: false
        position:
            type: smallint
            nullable: false
        size:
            type: smallint
            nullable: false
        rotated:
            type: boolean
            nullable: false
        dateCreation:
            type: datetime
            nullable: false
            column: date_creation
            gedmo:
                timestampable:
                    on: create
        dateUpdate:
            type: datetime
            nullable: false
            column: date_update
            gedmo:
                timestampable:
                    on: update
    lifecycleCallbacks: {  }
